# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 00:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('send_core', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('cookie', models.CharField(default='', max_length=200)),
                ('belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_core.Task')),
            ],
            options={
                'ordering': ['username', 'belongs'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('academisc', models.CharField(db_index=True, default='', max_length=20)),
                ('semester', models.CharField(db_index=True, default='', max_length=2)),
                ('courseCode', models.CharField(db_index=True, default='', max_length=30)),
                ('number', models.CharField(db_index=True, default='', max_length=30)),
                ('courseName', models.CharField(default='', max_length=100)),
                ('courseType', models.CharField(default='', max_length=100)),
                ('credit', models.CharField(default='', max_length=8)),
                ('totalGrade', models.CharField(db_index=True, default='', max_length=8)),
                ('makeupGrade', models.CharField(db_index=True, default='', max_length=8)),
                ('finalGrade', models.CharField(db_index=True, default='', max_length=8)),
                ('gradePoint', models.CharField(default='', max_length=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uestc_grade.Account')),
            ],
            options={
                'ordering': ['account', 'update_time'],
            },
        ),
    ]
