# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send_core', '0002_auto_20170516_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField()),
                ('plain', models.TextField(null=True)),
            ],
            options={
                'ordering': ['tracking_num'],
            },
        ),
        migrations.CreateModel(
            name='Tracking_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_num', models.CharField(db_index=True, max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('belongs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_core.Task')),
            ],
            options={
                'ordering': ['belongs'],
            },
        ),
        migrations.AddField(
            model_name='tracking',
            name='tracking_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='express_tracking.Tracking_num'),
        ),
    ]
