# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 00:25
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('author', models.CharField(db_index=True, max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('descript', models.TextField()),
                ('count', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('update_time', models.DateTimeField(default=datetime.datetime(2017, 5, 18, 0, 25, 18, 451112))),
                ('params', models.CharField(default='{"input": [{"type": "text", "name": "number", "value": "", "descript": "快递单号"}, {"type": "text", "name": "company", "value": "", "descript": "公司，点击下面按钮获取"}], "ajax": {"text": "获取公司"}}', max_length=1024)),
                ('ajax', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name', 'author'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, default=None, max_length=128)),
                ('link', models.URLField()),
                ('remain', models.IntegerField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Invited_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_invite', to=settings.AUTH_USER_MODEL)),
                ('who_invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_invite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time', 'person'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['task', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(db_index=True, max_length=200)),
                ('status', models.CharField(default='closed', max_length=200)),
            ],
            options={
                'ordering': ['target'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=128)),
                ('status', models.CharField(default='', max_length=128)),
                ('success', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('last_exec', models.DateTimeField(blank=True)),
                ('next_exec', models.DateTimeField(blank=True)),
                ('params', models.CharField(default='{}', max_length=2048)),
                ('check', models.IntegerField(default=0)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_task', to='send_core.Function')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_task', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id', 'person', 'function'],
            },
        ),
        migrations.AddField(
            model_name='log',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_task', to='send_core.Task'),
        ),
    ]
