# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 00:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('send_core', '0002_auto_20170516_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('text', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_task', to='send_core.Task')),
            ],
            options={
                'ordering': ['task', 'time'],
            },
        ),
        migrations.AlterField(
            model_name='function',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 17, 0, 33, 55, 571334)),
        ),
    ]
