# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 00:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_core', '0005_auto_20170517_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 18, 0, 3, 58, 305690)),
        ),
    ]
